### ISSUE TITLE
插件与 Matery 主题相冲突？

### ISSUE THREAD

**Issue by Johnzhu-123** [rqh656418510/hexo-readmore#3]
我在实践的过程中发现，hexo-readmore 插件似乎会与Matery主题文件相冲突，导致TOC目录锚点失效，出现这种情况除了更换主题，是否还有更好的办法？请大佬支招。

**Comment by rqh656418510** [comment]
请问是文章解锁后，TOC 目录锚点失效吗？最好附上网站链接

**Comment by rqh656418510** [comment]
> 我在实践的过程中发现，hexo-readmore 插件似乎会与Matery主题文件相冲突，导致TOC目录锚点失效，出现这种情况除了更换主题，是否还有更好的办法？请大佬支招。

请问是文章解锁后，TOC 目录锚点失效吗？最好附上网站链接

**Comment by rqh656418510** [comment]
> 我在实践的过程中发现，hexo-readmore 插件似乎会与Matery主题文件相冲突，导致TOC目录锚点失效，出现这种情况除了更换主题，是否还有更好的办法？请大佬支招。

或者添加一个插件配置参数试试，控制不锁住文章目录

``` yml
readmore:
  enable: true
  lockToc: false    // 是否锁住文章目录
  ...
```

**Comment by Johnzhu-123** [comment]
> > 我在实践的过程中发现，hexo-readmore 插件似乎会与Matery主题文件相冲突，导致TOC目录锚点失效，出现这种情况除了更换主题，是否还有更好的办法？请大佬支招。
> 
> 请问是文章解锁后，TOC 目录锚点失效吗？最好附上网站链接

是的，验证解锁后失效，网站链接：https://seeyjys.live/2024/03/28/ai-shi-dai-ni-de-sou-suo-li-huan-chong-ying-ma/

**Comment by Johnzhu-123** [comment]
> > 我在实践的过程中发现，hexo-readmore 插件似乎会与Matery主题文件相冲突，导致TOC目录锚点失效，出现这种情况除了更换主题，是否还有更好的办法？请大佬支招。
> 
> 或者添加一个插件配置参数试试，控制不锁住文章目录
> 
> ```yaml
> readmore:
>   enable: true
>   lockToc: false    // 是否锁住文章目录
>   ...
> ```

已经尝试，TOC 依旧失效

**Comment by Johnzhu-123** [comment]
其他插件信息如下：
![插件配置](https://github.com/rqh656418510/hexo-readmore/assets/87792450/a85c37fc-95e5-4425-82f6-c54e3bcdfbca)

**Comment by rqh656418510** [comment]
> > > 我在实践的过程中发现，hexo-readmore 插件似乎会与Matery主题文件相冲突，导致TOC目录锚点失效，出现这种情况除了更换主题，是否还有更好的办法？请大佬支招。
> 
> > 
> 
> > 请问是文章解锁后，TOC 目录锚点失效吗？最好附上网站链接
> 
> 
> 
> 是的，验证解锁后失效，网站链接：https://seeyjys.live/2024/03/28/ai-shi-dai-ni-de-sou-suo-li-huan-chong-ying-ma/

OK，有空我处理一下兼容问题。

**Comment by rqh656418510** [comment]
肝了一晚上☀️，Matery 主题的兼容性问题应该初步解决了，具体操作步骤如下：

- 1) 更新 Hexo 引流插件

``` sh
# 卸载已安装的引流插件
npm uninstall hexo-readmore --save

# 安装最新版的引流插件
npm install hexo-readmore --save
```

- 2) 新增两个插件配置参数

``` yml
readmore:
  # 文章目录的 JS 选择器
  tocSelector: '#toc-content'
  # 文章主体内容所在容器（DIV 标签）的 ID，在存在兼容性问题时才需要根据不同的主题进行配置
  articleContentId: 'articleContent'
```

- 3) 重新构建博客

``` sh
# 清理
hexo clean

# 构建
hexo generate
```

[官方文档](https://docs.techgrow.cn/v1/wechat/tutorial/hexo/#主题兼容问题)已同步更新，开源不易，如果兄弟觉得这个项目还 OK，希望能给项目一个宝贵的 Star :grinning::grinning::grinning:
